name: Build MUZEI

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  start_building_muzei:
    runs-on: ubuntu-22.04
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Set ANDROID_HOME (if needed)
      run: echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
    - name: Prepare environment
      run: |
        sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
        sudo apt update
        sudo apt upgrade -y
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Cache Gradle
      uses: burrunan/gradle-cache-action@v2
    - name: Get next version code
      id: next_ver_code
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG=$(gh release list -L 1 | awk -F '\t' '{print $3}')
        if [ -z "$TAG" ]; then TAG=0; fi
        echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT
    - name: Execute build script
      run: bash ./build.sh
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
    - name: Release MUZEI
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./prebuilt/*
        tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
        overwrite: true
        body: "MUZEI Release Synced With MUZEI SOURCE CODE"
        file_glob: true
